branch-defaults:
  main:
    environment: Cloudjourneysvpc-env
environment-defaults:
  Cloudjourneysvpc-env:
    branch: null
    repository: null
global:
  application_name: cloudjourneys-vpc
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2.14.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
